### ISSUE TITLE
GLSL resources

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [kosmos/awesome-generative-art#1]
book: thebookofshaders.com
editor: editor.thebookofshaders.com (https://github.com/patriciogonzalezvivo/glslEditor)
raspberrypi player: https://github.com/patriciogonzalezvivo/glslViewer
WebGL player: https://github.com/patriciogonzalezvivo/glslCanvas
gallery: https://github.com/patriciogonzalezvivo/glslGallery
Learning material: pixelspiritdeck.com

**Comment by kosmos** [comment]
Thanks. I will add!
